version: '3.8'

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  # app:
  #   image: ghcr.io/loan-mgt/referral-paradise:latest
  #   ports:
  #     - "8020:8080"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_NAME=${DB_NAME}
  #     - DB_HOST=db
  #     - DB_PORT=${DB_PORT}
  #     - SALT=${SALT}
  #   volumes:
  #     - .:/app

volumes:
  db_data:
